topic: flightatc

brokerAddress: 124.0.0.1:9092
groupId: foo
sessionTimeOut: 15000
autoOffsetReset: earliest

#spring:
#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#
#    consumer:
#      group-id: foo
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
